name: linter-check
on: push
jobs:
  my-job:
   runs-on: ubuntu-latest
   steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: ^3.10 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: linter
        run: make lint
